# Generated by Django 5.2 on 2025-05-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcard',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
